const USER_ROLES = {
  ADMIN: "ADMIN",
  SUPPLIER: "SUPPLIER",
  DELIVERYMANAGER: "DELIVERYMANAGER",
  RIDER: "RIDER",
  EMPLOYEEMANAGER:"EMPLOYEEMANAGER",
  EMPLOYEE:"EMPLOYEE",
  CUSTOMER:"CUSTOMER",
  RESERVATIONMANAGER: "RESERVATIONMANAGER",
  INVENTORYMANAGER: "INVENTORYMANAGER",
  ORDERMANAGER:"ORDERMANAGER",
  CUSTOMERMANAGER:"CUSTOMERMANAGER",
  CUSTOMERAFFAIRSMANAGER:"CUSTOMERAFFAIRSMANAGER"
};

module.exports = USER_ROLES;
