const USER_ROLES = {
  ADMIN: "ADMIN",
  SUPPLIER: "SUPPLIER",
  DELIVERYMANAGER: "DELIVERYMANAGER",
  RIDER: "RIDER",
  EMPLOYEEMANAGER:"EMPLOYEEMANAGER",
  EMPLOYEE:"EMPLOYEE",
  CUSTOMER:"CUSTOMER",
};

module.exports = USER_ROLES;
